# Generated by Django 3.1.7 on 2021-03-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210311_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=1000, verbose_name='Пароль'),
        ),
    ]
