# Generated by Django 3.1.7 on 2021-03-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20210311_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(unique=True)),
                ('name_of_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Типы',
                'verbose_name_plural': 'Типы',
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000, verbose_name='Текст записи')),
                ('slug_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='адрес записи')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Автор записи')),
                ('type_of_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.types', verbose_name='Тип записи')),
            ],
            options={
                'verbose_name': 'Записи',
                'verbose_name_plural': 'Записи',
                'db_table': 'note',
            },
        ),
    ]
