# Generated by Django 3.1.7 on 2021-03-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_url', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'Ссылки',
                'verbose_name_plural': 'Ссылки',
                'db_table': 'address',
            },
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Записи', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=5000, verbose_name='Текст записи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=1000, verbose_name='Пароль'),
        ),
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AddField(
            model_name='note',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.address', verbose_name='адрес записи'),
        ),
    ]
