# Generated by Django 3.1.7 on 2021-04-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_title'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['text'], name='text_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['date'], name='date_note_idx'),
        ),
        migrations.AddIndex(
            model_name='type',
            index=models.Index(fields=['name_of_type'], name='name_idx'),
        ),
    ]
