# Generated by Django 3.1.7 on 2021-03-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210316_1218'),
        ('notes', '0002_auto_20210312_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_author', to='users.user', verbose_name='Автор записи'),
        ),
    ]
