# Generated by Django 3.1.7 on 2021-03-10 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210310_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(unique=True)),
                ('name_of_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Типы',
                'verbose_name_plural': 'Типы',
                'db_table': 'types',
            },
        ),
        migrations.RemoveField(
            model_name='note',
            name='address',
        ),
        migrations.AddField(
            model_name='note',
            name='slug_address',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='адрес записи'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='note',
            name='type_of_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.types', verbose_name='Тип записи'),
        ),
    ]
