# Generated by Django 3.1.7 on 2021-03-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210310_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug_address',
            field=models.CharField(max_length=100, unique=True, verbose_name='адрес записи'),
        ),
    ]
