# Generated by Django 3.1.7 on 2021-03-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210310_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type_of_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.types', verbose_name='Тип записи'),
        ),
    ]
