# Generated by Django 3.1.7 on 2021-03-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20210310_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='адрес записи'),
        ),
    ]
