# Generated by Django 3.1.7 on 2021-03-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20210310_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='адрес записи'),
        ),
    ]
